# Generated by Django 4.1.7 on 2023-05-10 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reqName', models.CharField(max_length=50)),
                ('gradeNum', models.DecimalField(decimal_places=2, max_digits=5)),
                ('subName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.subject')),
            ],
        ),
    ]
