# Generated by Django 4.1.7 on 2023-05-10 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_requirement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reqID', models.IntegerField()),
                ('reqName', models.CharField(max_length=50)),
                ('dueDate', models.DateTimeField()),
            ],
        ),
    ]
