# Generated by Django 4.1.7 on 2023-05-10 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_task2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task2',
        ),
        migrations.RemoveField(
            model_name='task',
            name='reqID',
        ),
        migrations.AddField(
            model_name='task',
            name='taskName',
            field=models.CharField(default='Gab', max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='reqName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.requirement'),
        ),
    ]
