# Generated by Django 4.1.7 on 2023-05-10 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_delete_task2_remove_task_reqid_task_taskname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='taskName',
            field=models.CharField(default='', max_length=50),
        ),
    ]
