# Generated by Django 4.1.7 on 2023-05-10 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0007_remove_task_taskname_alter_task_reqname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='reqName',
        ),
        migrations.AddField(
            model_name='subject',
            name='gradeNum1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='subject',
            name='gradeNum2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='subject',
            name='gradeNum3',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='subject',
            name='gradeNum4',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='subject',
            name='gradeNum5',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='subject',
            name='reqName1',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='subject',
            name='reqName2',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='subject',
            name='reqName3',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='subject',
            name='reqName4',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='subject',
            name='reqName5',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='task',
            name='taskName',
            field=models.CharField(default='', max_length=50),
        ),
    ]
