# Generated by Django 4.1.7 on 2023-05-10 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0008_remove_task_reqname_subject_gradenum1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='reqType',
            field=models.CharField(default='', max_length=50),
        ),
    ]
