# Generated by Django 4.1.7 on 2023-05-10 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hello", "0009_task_reqtype"),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='subName',
            field=models.ForeignKey(default=18, on_delete=django.db.models.deletion.CASCADE, to='hello.subject'),
            preserve_default=False,
        ),
    ]
