# Generated by Django 4.1.7 on 2023-05-10 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0010_task_subname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='subName',
        ),
    ]
