# Generated by Django 4.1.7 on 2023-05-11 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0010_task_subname'),
    ]

    operations = [
        migrations.CreateModel(
            name='DegreeProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degName', models.CharField(max_length=255)),
                ('jsonData', models.JSONField()),
            ],
        ),
    ]
