# Generated by Django 4.1.7 on 2023-05-10 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0011_remove_task_subname'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='subName',
            field=models.CharField(default='', max_length=50),
        ),
    ]
