# Generated by Django 4.2.1 on 2023-05-11 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hello", "0011_degreeprogram"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="subEnd",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="subject",
            name="subStart",
            field=models.DateTimeField(null=True),
        ),
    ]
