# Generated by Django 4.1.7 on 2023-05-22 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0013_webuser_subject_enrolees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webuser',
            name='email',
            field=models.EmailField(default='...', max_length=254, unique=True, verbose_name='User Email'),
        ),
        migrations.AlterField(
            model_name='webuser',
            name='firstName',
            field=models.CharField(default='...', max_length=25, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='webuser',
            name='lastName',
            field=models.CharField(default='...', max_length=25, verbose_name='Last Name'),
        ),
    ]
