# Generated by Django 4.1.7 on 2023-05-22 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0014_alter_webuser_email_alter_webuser_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='User Email'),
        ),
        migrations.AlterField(
            model_name='webuser',
            name='firstName',
            field=models.CharField(max_length=25, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='webuser',
            name='lastName',
            field=models.CharField(max_length=25, verbose_name='Last Name'),
        ),
    ]
