# Generated by Django 4.1.7 on 2023-05-23 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hello', '0018_remove_task_enrolee_alter_subject_enrolee'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='enrolee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
