# Generated by Django 4.1.7 on 2023-05-23 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0019_task_enrolee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WebUser',
        ),
    ]
