# Generated by Django 4.2.1 on 2023-05-24 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hello", "0021_subject_subjdays"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="subEnd",
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name="subject",
            name="subStart",
            field=models.TimeField(null=True),
        ),
    ]
