# Generated by Django 4.2.1 on 2023-05-25 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hello", "0022_alter_subject_subend_alter_subject_substart"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="notes",
            field=models.TextField(default=""),
        ),
    ]
